### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by lostfictions** [bvaughn/redux-search#42]
Looks like `redux-search` implicitly depends on the Regenerator runtime being available as a global. This doesn't seem to be documented anywhere, and I hadn't been including `babel-polyfill` anywhere because I didn't need it for my particular environment.

My fix was pretty simple, but obviously this is going to be annoying for, say, anyone working in a non-Babel environment. (It's also not clear to me whether `redux-search`'s approach of relying on `regeneratorRuntime` existing as a global would play nicely with, say, `babel-plugin-transform-runtime` in a parent project, since it's already transformed.)

Incidentally, it would be really cool to see a minimal example project for `redux-search` that didn't share dependencies with its parent. Some stuff in this repo's `package.json` is probably only being used for the included example, but it's not very clear what's needed where.

**Comment by bvaughn** [comment]
Thanks for the feedback @lostfictions. I've updated the README to mention this explicitly for now.

When I find some free time (which may be a while) I'll try to put together a minimal example for you. If you beat me to it though, I'd be happy to link to it in the README.
