### ISSUE TITLE
createSearchAction not firing

### ISSUE THREAD

**Issue by baking89** [bvaughn/redux-search#53]
Hi, I have the following in my `index.js`

```js
const enhancers = composeWithDevTools(
  applyMiddleware(remoteActionMiddleware(socket)),
  reduxSearch({
    resourceIndexes: {
      recipes: ["title"]
    },
    resourceSelector: (resourceName, state) => {
      return state[resourceName];
    }
  })
);

const store = createStore(
  combineReducers({
    recipes: recipesReducer,
    editMode: editReducer,
    activeRecipe: activeRecipeReducer,
    search: searchReducer
  }),
  enhancers
);
```

then in a connected component:

```jsx
// in render():
<input
   onChange={event => {
      console.log("SEARCH", event.target.value);
      this.props.searchRecipes(event.target.value);
     }}
   placeholder='Search..'
 />
...

const recipes = state => state.recipes.toJS();

const {
  text, // search text
  result // ids
} = getSearchSelectors({
  resourceName: "recipes",
  resourceSelector: (resourceName, state) => state[resourceName]
});

const mapStateToProps = createSelector(
  [result, recipes, text],
  /* eslint-disable no-shadow */
  (ids, recipes, searchText) => ({
    ids,
    recipes,
    searchText
  })
);

const mapDispatchToProps = (dispatch) => ({
  searchRecipes: createSearchAction("recipes"),
  dispatch });

const wrap = connect(mapStateToProps, mapDispatchToProps);

export default withRouter(wrap(MyComponent));
```

The search runs on initial render (with no text), returning all results, as expected. However, although the `onChange` event is firing, no subsequent search actions are being dispatched. Is there anything wrong with my configuration?

Many thanks for this module :)

**Comment by bvaughn** [comment]
Hi @baking89,

Sorry for the slow response. I started a new job this week and I'm preparing for a conference this weekend so I'm very busy at the moment.

One small thought: You should probably pass `text` (the search text selector value) through to your search `<input>` to keep them in sync. This will be important if the user searches, navigates to a different state, and then navigates back to see a still-filtered list.

Your `store` setup looks fine at a glance and your connected component also seems reasonable. Hm. Might help if I could take a look at it / run it?

By the way, I modified your comment slightly to add js/jsx syntax highlighting. Hopefully that's ok.

**Comment by baking89** [comment]
Hi *bvaughn*,

Thats not a problem, it's just a little personal project - my first attempt at a redux app, feel free to check it out here https://github.com/baking89/recipes-app/tree/feature-search.

I'm using `redux-devtools-extension` alongside the chrome app https://github.com/zalmoxisus/redux-devtools-extension for debugging.

Cheers!

**Comment by bvaughn** [comment]
@baking89

Checked out your git repo. Afraid I don't see the search UI though. Did you forget to push it?

**Comment by baking89** [comment]
The code is https://github.com/baking89/recipes-app/blob/feature-search/client/components/RecipeList.jsx. 

The search implementation is on the landing page `localhost:4441/recipes`, although you will need to checkout the `feature-search` branch first (sorry I forgot to mention that!)

**Comment by bvaughn** [comment]
Ah, gotcha. I was looking at `master`.

This should fix your branch:

```diff
diff --git a/client/components/RecipeList.jsx b/client/components/RecipeList.jsx
index 05a712a..a38a93b 100644
--- a/client/components/RecipeList.jsx
+++ b/client/components/RecipeList.jsx
@@ -19,12 +19,14 @@ class RecipeList extends React.Component {
             <input
               onChange={event => {
                 console.log("SEARCH", event.target.value);
-                this.props.searchRecipes(event.target.value);
+                this.props.dispatch(this.props.searchRecipes(event.target.value));
               }}
               placeholder='Search..'
             />
           <Collection className="lime lighten-4 black-text">
-              {_.map(this.props.recipes, (recipe) => (
+              {_.map(this.props.ids, (id) => {
+                const recipe = this.props.recipes[id];
+                return (
                   <CollectionItem
                     onClick={() => {
                       this.props.router.push({ pathname: "/edit" });
@@ -35,7 +37,7 @@ class RecipeList extends React.Component {
                     {recipe.name}
                   </CollectionItem>
                 )
-              )}
+              })}
             </Collection>
           </Col>
         </Row>
diff --git a/client/index.js b/client/index.js
index 2e7b75b..cfbded3 100644
--- a/client/index.js
+++ b/client/index.js
@@ -25,7 +25,7 @@ const enhancers = composeWithDevTools(
   applyMiddleware(remoteActionMiddleware(socket)),
   reduxSearch({
     resourceIndexes: {
-      recipes: ["title"]
+      recipes: ["name"]
     },
     resourceSelector: (resourceName, state) => {
       return state[resourceName];
```

**Comment by baking89** [comment]
Ahh I wasn't `dispatch`-ing, that's embarrassing! Thank you so much for taking a look :)

**Comment by bvaughn** [comment]
No problem. 😁
