### ISSUE TITLE
Use in TypeScript Project

### ISSUE THREAD

**Issue by Renader** [bvaughn/redux-search#55]
Hello,

I had some issues running this in an Angular 2 project with TypeScript and angular cli. First of all the imports didn't work. I could solve that by adjusting the path to:

`import {  reducer as searchReducer, reduxSearch} from 'redux-search/dist/es/index.js'`
which feels kinda wrong..

secondly i receive Babel errors, how to avoid that?
`babelHelpers is not defined`

Your search seams to be **really great** but it would be nice to easier use it outside of React and Babel environment. :-)

**Comment by bvaughn** [comment]
Hm, well the problems are completely unrelated to React/Angular. Seems to be a TypeScript issue.

redux-search publishes 3 build targets: UMD (for `<script>` tag usage), CommonJS (for Webpack 1), and ES (for Webpack 2, Rollup, etc). The latter (Webpack 2 and Rollup) are still ironing out module issues as far as I can tell and as a result, they don't yet work quite right. But that's the idea.

I've used TypeScript for a few library projects, but not recently- and never with an application that imports other libraries like redux-search. So I'm not sure why it's giving you problems. (An error message or more info about "the imports didn't work" may be helpful, but no promises.)

I _can_ fix the `babelHelpers` issue for you though. In fact, it should already be fixed if you'll update to version 2.3.2.
