### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by StlthyLee** [bvaughn/redux-search#60]
I seem to be having trouble setting up redux-search in my project. Even though I've set it up in exactly the same way as displayed here [https://github.com/bvaughn/redux-search/blob/master/website/createAppStore.js](https://github.com/bvaughn/redux-search/blob/master/website/createAppStore.js) and using the information provided on the README, when I open my app in the browser to check that nothing is broken I am getting the following error: 

`Uncaught TypeError: Cannot read property 'get' of undefined`

The error is coming form this line: 

`return state.resources.get(resourceName);`

any ideas what could be causing this?

Here is the my createStore code: 

```
import { createStore as _createStore, applyMiddleware, compose } from 'redux';
import { reduxSearch } from 'redux-search';
import createMiddleware from './middleware/clientMiddleware';
import rootReducer from '../reducers/rootReducer';

export default function createStore(history, client, data) {
  // Sync dispatched route actions to the history
  const middleware = [createMiddleware(client)];
  let finalCreateStore;
  if (__DEVELOPMENT__ && __CLIENT__ && __DEVTOOLS__) {
    finalCreateStore = compose(
      applyMiddleware(...middleware),
      reduxSearch({
        resourceIndexes: {
          users: ['name'],
        },
        resourceSelector: (resourceName, state) => {
          return state.resources.get(resourceName);
        },
      }),
      // The code below is needed to make chrome Redux dev tools work.
      // window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
    )(_createStore);
  } else {
    finalCreateStore = applyMiddleware(...middleware)(_createStore);
  }
  const store = finalCreateStore(rootReducer, data);
  return store;
}
```
![screen shot 2017-02-14 at 09 20 26](https://cloud.githubusercontent.com/assets/36741/22922748/e3df4e68-f296-11e6-8501-b032bfbd8083.png)

Any help would be appreciated.

Thanks in advance

**Comment by StlthyLee** [comment]
After doing a bit more digging (not a huge amount admittedly) it would appear that the resources map is not being added to the state.

**Comment by bvaughn** [comment]
What does your root reducer look like? The `resourceSelector` you're passing the store (in the code you copied above) is returning: `state.resources.get(resourceName)`

This means it's assuming there is a `resources` node at the top level of your Redux store and that it is an Immutable object (or something else that implements `get`). The error you've pasted would suggest that this is not the case.

**Comment by StlthyLee** [comment]
Thanks for replying,

here is the rootReducer

```
import { combineReducers } from 'redux';
import multireducer from 'multireducer';
import { routerReducer } from 'react-router-redux';
import { reducer as reduxAsyncConnect } from 'redux-connect';
import { reducer as searchReducer } from 'redux-search';
import { reducer as form } from 'redux-form';
import app from './appReducer';
import assets from './assetsReducer';
import auth from './authReducer';
import dataObjects from './dataObjectsReducer';
import devices from './devicesReducer';
import dialog from './dialogReducer';
import endlessAisles from './endlessAisleReducer';
import filter from './filterReducer';
import folderChooser from './folderChooserReducer';
import navigation from './navigationReducer';
import navigationGroup from './navigationGroupReducer';
import notifications from './notificationsReducer';
import playlists from './playlistsReducer';
import roles from './rolesReducer';
import schedules from './schedulesReducer';
import sequences from './sequencesReducer';
import signs from './signsReducer';
import sites from './sitesReducer';
import urlRulesets from './urlRulesetReducer';
import users from './usersReducer';

const rootReducer = combineReducers({
  routing: routerReducer,
  search: searchReducer,
  filter,
  reduxAsyncConnect,
  app,
  assets,
  auth,
  dataObjects,
  devices,
  dialog,
  endlessAisles,
  signs,
  form,
  folderChooser,
  playlists, /* Should all data based entries be wrapped? */
  roles,
  schedules,
  sequences,
  sites,
  urlRulesets,
  users,

  multireducerNavigationGroup: multireducer({
    content: navigationGroup,
    devices: navigationGroup,
    schedules: navigationGroup,
    sequences: navigationGroup,
    signs: navigationGroup,
    modules: navigationGroup,
    sites: navigationGroup,
    admin: navigationGroup,
  }),
  navigation,
  notifications,
});

export default rootReducer;
```

**Comment by StlthyLee** [comment]
Actually, looking back over the example code in /website and your comment I think I can see what you're meaning. the example you give in the Readme doesn't make mention of a resources reducer I think this may be where I got confused.

**Comment by bvaughn** [comment]
Your root reducer doesn't specify a `resources` node.

Looking at the `resourceIndexes` you've specified, it looks like you only want to search `users` in which case your `resourceSelector` should just be: `return state.users;`

**Comment by StlthyLee** [comment]
yes, you are right. Thanks for your help.

**Comment by bvaughn** [comment]
No problem.

**Comment by rememberlenny** [comment]
This comment tree might be worth adding to the overall documentation. I hit the same error.
