### ISSUE TITLE
Redux-search + Redux-immutable

### ISSUE THREAD

**Issue by arieldf** [bvaughn/redux-search#62]
I am working on a project where we are using an immutable redux store where the initial state of the app is an Immutable.Map() (see https://github.com/gajus/redux-immutable). Is there an easy way to get redux-search to work with this setup?

I get this error: "Can not read property "menuItems" of undefined", where "menuItems" is my resource index. Having the top-level of the state as a plain JS object works just fine.

**Comment by arieldf** [comment]
I ended up having a split state (plain/immutable) at root level which is perfectly fine in my case.

**Comment by bvaughn** [comment]
Glad you got it sorted :)
