### ISSUE TITLE
resourceSelector documentation and usage

### ISSUE THREAD

**Issue by slavab89** [bvaughn/redux-search#63]
So i've started integrating your library to allow searches on my website and it was quite difficult to understand (even with the examples and documentation) on how to do it.

The main thing that stopped me was the usage of `resourceSelector` property in `reduxSearch` function.
The documentation says that you may omit it if you want to manage the index manually, yet i didnt find any information on how to do it - Did you mean the manual creation of a different SearchApi class?
If i did not include the `resourceSelector` property then all fired actions would fail with an exception.

Moreover, does `resourceSelector` must return an object with the following format?
```js
{
  '1': { /* actual object with id:1 property */},
  '2': { /* actual object id:2 property */}
  '3': { /* actual object id:3 property */}
}
```
What if my actual data is held in a array of objects? I thought that the mapping should have been created by using `resourceIndexes` definition (that will create the mapping from `id` to `company_name` or something like that)

I'm sorry for all the (basic?) questions, i was not able to find any information on that in SO or other issues.

**Comment by bvaughn** [comment]
Admittedly, I haven't spent a ton of time on the docs for this library. I apologize that you found them difficult to work with. I would love to get a PR (or more!) from you to improve the documentation once you have a better idea of how the library works.

> The main thing that stopped me was the usage of `resourceSelector` property in `reduxSearch` function. The documentation says that you may omit it if you want to manage the index manually, yet i didnt find any information on how to do it

If you specify this selector, then each time your redux resources are updated a search will [automatically be rebuilt](https://github.com/bvaughn/redux-search/blob/c1279be6aa25b9264a380873b569457b40b6be78/source/reduxSearch.js#L57). This is probably the most convenient way to use redux-search but maybe it's not as performant. If you _know_ that resources aren't always searched, you can defer building the search index. If you want to manually manage the index, you can dispatch the [`indexResource ` action](https://github.com/bvaughn/redux-search/tree/master/docs#indexresource-resourcename-fieldnamesorindexfunction-resources) directly.

**Comment by slavab89** [comment]
Thanks for the clarification about the manual bulding of the indexResource action.

The resourceSelector can be any collection (array or object), that is correct.
However, for it to work with an array, it seems that i'll need to provide a different `filterFunction` in the selector itself due to the nature of it. (When working with regular JS array) https://github.com/bvaughn/redux-search/blob/master/source/selectors.js#L50
Or at least have another mapping between id and some object. 
For performance, i guess i'll better have some additional mapping if i want to get the actual objects in the selector function. doing `array.find()` on each resultId can be quite hard.

**Comment by bvaughn** [comment]
> Say i have books and students, each in its own reducer. Should i have the indexResource mapping be books.data and students.data? Or define an specific index function for each one of them?

Each should be a separate key in the `resourceIndexes` object since you would, presumably, not want results to be mixed? (I assume your app would allow people to search for students _or_ books- not both together.)

> The resourceSelector can be any collection (array or object), that is correct.

Sorry, I misspoke. I meant to say immutable map or object.

**Comment by slavab89** [comment]
yeah, each of them is searched independently. Was just wondering about the convention of the key names, cause i have a resourceName and state, and with that i should be able to get to different reducers.

Thanks a lot 👍 👍
