### ISSUE TITLE
Passing `undefined` to `indexDocument`.

### ISSUE THREAD

**Issue by AndyCJ** [bvaughn/redux-search#69]
I'm passing `undefined` to `indexDocument` as the second parameter (i.e. the text to be indexed) and this is causing some errors to occur.

The first error is obvious enough, you can't call members of undefined:

    Uncaught TypeError: Cannot read property 'trim' of undefined
        at SearchUtility._sanitize (blob:XXXXX:368)
        at SearchUtility.indexDocument (blob:XXXXX:175)
        at blob:XXXXX:69
		
The second appears to occur in the error handling trigger by the first error:
		
    webpack-internal:///359:671 Uncaught TypeError: Cannot read property 'callbackId' of undefined
        at Worker.SearchWorkerLoader._worker.onerror (webpack-internal:///359:671)

I can "fix" these errors by simply not passing `undefined` to `indexDocument`.

Is there any way to enable handling undefined values either as an option for the library, or some global hook where I can change this behavior globally?

If there isn't, then is this a reasonable approach to handling this in my own code?

    const projectIndexer: ReduxSearch.ResourceIndexer<Models.Project[], StoreModule.ApplicationState> = ({ resources, indexDocument, state }) => {
        const safeIndexDocument = (id: string, text?: string) => {
            if (text != undefined) {
                indexDocument(id, text);
            }
        };
    
        resources.forEach(project => {
            if (project && project.id != undefined) {
                safeIndexDocument(project.id, project.name);
    			safeIndexDocument(project.id, project.reference);
            }
        });
    };

And finally, I don't think the error handling should be causing further errors for this issue, so maybe an extra check is needed?

**Comment by bvaughn** [comment]
> I'm passing undefined to `indexDocument` as the second parameter

This isn't supported. This method expects a string to build a search index from.

> If there isn't, then is this a reasonable approach to handling this in my own code?

You could pass an empty string ([like the default implementation does](https://github.com/bvaughn/redux-search/blob/e7b4302d0176cf6a2bd3026f32b21912d99ba139/source/SearchApi.js#L73)) or better yet- just don't call `indexDocument` if you have no text to index for a given document.

> And finally, I don't think the error handling should be causing further errors

I agree this should not be happening. I'll add a fix for this upstream in [js-worker-search](https://github.com/bvaughn/js-worker-search) which is where that code lives.

**Comment by bvaughn** [comment]
Upstream fix ([8ee2b5e](https://github.com/bvaughn/js-worker-search/commit/8ee2b5e2e0f1bbe9e4ceda0e849597eca6c6d9c5)) published as [js-worker-search@1.2.1](https://github.com/bvaughn/js-worker-search/blob/master/CHANGELOG.md#121).

**Comment by AndyCJ** [comment]
Thanks for the info!
