### ISSUE TITLE
Reindexing causes browser crashes

### ISSUE THREAD

**Issue by LrsK** [bvaughn/redux-search#70]
I'm not sure if this belongs here or in js-worker-search, but when using redux-search I can reproduce the issue.

I have an app where I use redux-search to filter results from a remote server. This means reindexing the search data after a fetch. After a few clicks that fetches data and then indexes the data, the browser or browser tab crashes.

I was unable to code up a reliable repro myself, but the [redux-search demo app](https://bvaughn.github.io/redux-search/) will exhibit this behavior if you click back and forth and re-click a lot on the "Generate Data"-buttons. This might seem silly since there is a lot of clicking that happens, but in my app, this sometimes happens after a couple of navigation clicks.

This happens more often in Chrome than in Firefox, where Chrome seems to crash quickly, while Firefox seems to crash "slowly" but more forcefully, I'm not sure why it happens more easily in my app, but the big difference from the demo code is that I have a fetch in between each click which probably causes more of a delay.

GIF showing what happens:
![reduxsearch_crash](https://user-images.githubusercontent.com/827702/39295707-62c35738-493f-11e8-812d-921e3da7f342.gif)

**Comment by bvaughn** [comment]
Seems most likely to be something that should be reported against js-worker-search but I don't know without taking a look and I don't have the bandwidth to dig in right now. I'd love a PR if you are able to get to the bottom of it though! 😄

**Comment by AndyCJ** [comment]
We're seeing this in one of our applications, now that the amount data in the app is growing to be fairly large.

It appears to be a memory leak, which I think is caused by a new service worker being spun up for each reindex, but then not cleaned up. I'll try figure out more and let you know if I manage to figure out anything.

I've not personally done anything with workers, so I guess this will be a chance to learn some new stuff!

**Comment by LrsK** [comment]
I have looked at this a little bit as well and it is much harder to recreate the issue on machines that are fast and have a lot of CPU threads, so this may mean that the workers are not finishing in time for the next worker is started. So my theory is that the number of concurrent workers is exceeding a certain threshold, which then causes the crash.

One approach would be to create a pool to web workers and use one of these to perform the indexing task. A reasonable number of workers could be based on [window.navigator.hardwareConcurrency](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency).

**Comment by LrsK** [comment]
A worker pool may not work after all, since the problem arises, for me at least, when overworking the indexing. If a pool of workers were created for each index in redux-search, this would probably make the problem worse. 

Perhaps making the indexDocument in js-worker-search return a promise, and then having indexResource in redux-search use the promises to restrict reindexing if all the indexing is not finished?

**Comment by LrsK** [comment]
Further investigation has revealed that the reason for the crash is that the machine runs out of free memory, and the process is killed. It seems that something is not being GC'ed properly.

Here is a video of how my Linux machine responds to exactly 14 generate-clicks:
![reduxsearch_crash2](https://user-images.githubusercontent.com/827702/39926823-afb9b210-5530-11e8-833e-9551578b66b7.gif)

It takes the same number of clicks each time.

**Comment by bvaughn** [comment]
> Perhaps making the indexDocument in js-worker-search return a promise, and then having indexResource in redux-search use the promises to restrict reindexing if all the indexing is not finished?

Hm... 🤔 maybe `indexDocument` could be updated to return a promise (not sure how much overhead this would add when you're indexing _many_ documents). More importantly though, maybe it should be updated to automatically throttle or serialize indexing in some way to prevent overuse like this.

**Comment by LrsK** [comment]
I've been reading up on Web Workers and memory usage. It seems that if a large amount of data is sent back and forth between main and worker, some data will remain unless handed back to the worker. As [can be seen in the postMessage docs](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage), you can send a transferable object between worker and main to free up some memory. The data needs to be "transferable" though, and seems to mean that the data needs to be serialized before sending. 

I have made a codepen of the needed code here:
https://codepen.io/lrsk/pen/PeeOyp?editors=0010

If this is opened in Chrome and you open a memory usage watcher, you will see a difference when the following line is added or removed:
`searchWorker.postMessage("res", [e.data]);`

This is the part that needs to be added to js-worker-search, and of course the serialization part.

What do you guys think?

**Comment by bvaughn** [comment]
I don't really understand what you're proposing to be honest. If you'd like to put a PR together, I'll take a look? 😄

**Comment by LrsK** [comment]
I have a fix ready that will mitigate the memory leak, it relies on a PR being accepted in js-worker-search.

Another approach that does not require a change in js-worker-search is to reuse the same SearchApi instance, for all indexing given the same resourceName, but I ran into problems there since there is no "reindex" method in the SearchApi and so the index will continue growing if the data changes.

**Comment by bvaughn** [comment]
Bugfix published as v2.4.1

Sorry for the delay!
