### ISSUE TITLE
Does not reindex if data is dependant on 2 substates

### ISSUE THREAD

**Issue by jinixx** [bvaughn/redux-search#72]
See below example, ids are dynamic, names are async, scenario could be when an item is added to saved list array, follow by async loading of name (and/or name could be changed real time):

```
state: {
  savedItems: ['key1', 'key3'],
  allItemsInfo: { 
    key1: { name: 'item name 1', id: 'key1' },
    key2: { name: 'item name 2', id: 'key2' },
    key3: { id: 'key3' },
    ...
  },
}
```

the savedItems state is indexed as per below, so it's searchable by name or id:

```
savedItems: ({ resources, indexDocument, state }) => {
  resources.forEach(id => {
    if (state.allItemsInfo[id].name) indexDocument(id, state.allItemsInfo[id].name);
    indexDocument(id, state.allItemsInfo[id].id);
  });
},
```

Searching for id's will work as expected, however, if name wasn't available when savedItems was indexed or name is changed in real time, it does not reindex, as it only reindex when savedItems is changed.

Am I doing it wrongly or is there a way to subscribe to changes on 2 substates?

**Comment by bvaughn** [comment]
> if name wasn't available when savedItems was indexed or name is changed in real time, it does not reindex, as it only reindex when savedItems is changed.

Sounds like expected behavior to me.

**Comment by jinixx** [comment]
Thanks for the response. But is there a way to trigger a reindex when one of two substates changes ? Other than creating another substate with duplicated data derived from both.

**Comment by bvaughn** [comment]
I don't know, sorry. I haven't used this library myself in about two years 😅

**Comment by bvaughn** [comment]
I think this is working as expected so I'm going to close the issue.

Sorry I wasn't more helpful in terms of suggestions. If you have suggestions for docs improvements based on your own findings, please open a PR with them! 😄
