### ISSUE TITLE
Switching resourceIndexes / fields in resourceIndex

### ISSUE THREAD

**Issue by JMStewart00** [bvaughn/redux-search#79]
I'm wondering if it's possible to switch what has been indexed on the fly or limit the field within the index that is being referenced. For example if your resourceIndex includes the resource of books with the fields of author and title, would it be possible to search just the title? (i.e. one book has an author of John Doe and another has a title of John Doe's autobiography, but based on user input they would only want the book title of John Doe's autobiography).

In a current project I have I'm indexing just one resource, but how it is referenced/filtered can be user selected and we are trying to figure out how to switch indexes based on the user request.

We know we could maintain multiple indexes, but we are worried about the memory footprint with managing 7+ indexes for up to two thousand items.

**Comment by bvaughn** [comment]
No, that would need to be done with separate indexes (that you could then take the union of if you wanted to search multiple fields at once). Sorry!

**Comment by JMStewart00** [comment]
@bvaughn quite alright. Thanks for getting back to me!
